import test from 'node:test';
import assert from 'node:assert/strict';
import {createStackedPlaySession} from '../apps/stacked/src/play-session.mjs';
import {createStackedPortalLifecycle} from '../apps/portal/src/stacked-portal-lifecycle.mjs';
const load=()=>import('../apps/portal/src/stacked-daily-challenge.mjs');
const now=Date.parse('2026-09-30T23:59:59.999Z');
const session=()=>({gameId:'stacked',mode:'free',leaderboardEligible:false,seed:44,buildHash:'stacked-test',seasonId:'stacked-season-preview-1',sessionId:'free-daily',canonicalContext:Object.freeze({seed:44,mode:'free'})});
const memory=()=>{const data=new Map();return{data,getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};};
async function bound(){return(await load()).bindStackedDailyChallenge(session(),{now});}
async function finished(s){const run=createStackedPlaySession({...s,mode:'free',startLevel:1});while(!run.result)run.step(run.snapshot.tick%2?0:8);const lifecycle=createStackedPortalLifecycle({session:s,persistRanked:()=>assert.fail('daily cannot persist Ranked')});return{run,result:await lifecycle.finish(run.evidence(),run.result)};}
test('UTC day is fixed at issuance and rejects invalid dates',async()=>{const m=await load();assert.equal(m.utcStackedDayKey(now),'2026-09-30');assert.equal(m.utcStackedDayKey(now+1),'2026-10-01');assert.equal(m.utcStackedDayKey('2026-10-01T00:30:00+02:00'),'2026-09-30');assert.throws(()=>m.utcStackedDayKey(NaN));});
test('daily seed has fixed golden values and rejects impossible calendar days',async()=>{const m=await load();assert.equal(m.deriveStackedDailySeed('2026-09-30'),1885307033);assert.equal(m.deriveStackedDailySeed('2026-10-01'),2534331135);for(const d of ['2026-02-29','2026-04-31','2026-1-01',' 2026-09-30','2026-09-30x'])assert.throws(()=>m.deriveStackedDailySeed(d));assert.ok(m.deriveStackedDailySeed('2024-02-29')>0);});
test('parent binds an immutable daily descriptor and canonical seed without mutating session',async()=>{const m=await load(),old=session(),s=m.bindStackedDailyChallenge(old,{now});assert.equal(s.seed,m.deriveStackedDailySeed('2026-09-30'));assert.equal(s.canonicalContext.seed,s.seed);assert.equal(old.seed,44);assert.equal(old.canonicalContext.seed,44);assert.equal(s.dailyChallenge.dayKey,'2026-09-30');assert.ok(Object.isFrozen(s.dailyChallenge));assert.equal(m.dailyChallengeForSession(s).dayKey,'2026-09-30');});
test('Ranked, paid, unknown mode and incomplete eligibility preserve seed and clear daily identity',async()=>{const m=await load();for(const change of [{mode:'ranked'},{mode:'paid'},{mode:undefined},{leaderboardEligible:true},{leaderboardEligible:undefined}]){const old={...session(),...change,dailyChallenge:{dayKey:'2026-09-30'}},next=m.bindStackedDailyChallenge(old,{now});assert.equal(next.seed,44);assert.equal(next.canonicalContext.seed,44);assert.equal(next.dailyChallenge,null);}assert.throws(()=>m.bindStackedDailyChallenge({...session(),gameId:'chikun'},{now}));});
test('daily identity fails closed for changed seed, version or date',async()=>{const m=await load(),s=await bound();for(const next of [{...s,seed:s.seed+1},{...s,mode:'paid'},{...s,dailyChallenge:{...s.dailyChallenge,version:'other'}},{...s,dailyChallenge:{...s.dailyChallenge,dayKey:'2026-09-31'}},{...s,dailyChallenge:{...s.dailyChallenge,extra:true}}])assert.equal(m.dailyChallengeForSession(next),null);});
test('same day replays byte-identically through existing lifecycle; next day rejects old evidence',async()=>{const m=await load(),s=await bound(),{run,result}=await finished(s);assert.equal(result.ok,true);assert.deepEqual(result.canonical,run.result);const same=m.bindStackedDailyChallenge(session(),{now:now-60000}),repeat=await finished(same);assert.deepEqual(repeat.run.evidence(),run.evidence());assert.deepEqual(repeat.result.canonical,result.canonical);const next=m.bindStackedDailyChallenge(session(),{now:now+1}),life=createStackedPortalLifecycle({session:next});assert.equal((await life.finish(run.evidence(),run.result)).ok,false);});
test('only an accepted, unranked, identity-matching canonical result writes local daily storage',async()=>{const m=await load(),s=await bound(),{result}=await finished(s),storage=memory();for(const r of [{...result,ok:false},{...result,ranked:true},{...result,canonical:{...result.canonical,seed:1}},{...result,canonical:{...result.canonical,buildHash:'other'}},{...result,canonical:{...result.canonical,seasonId:'other-season'}},{...result,canonical:{...result.canonical,score:Infinity}}])assert.equal(m.completeStackedDaily(s,r,storage),null);assert.equal(storage.data.size,0);const r=m.completeStackedDaily(s,result,storage);assert.equal(r.saved,true);assert.equal(r.first,true);assert.equal(r.bestScore,result.canonical.score);assert.equal(storage.data.size,1);assert.ok(storage.data.has(m.STACKED_DAILY_STORAGE_KEY));});
test('daily best keeps higher scores, reports gap and does not award ties',async()=>{const m=await load(),s=await bound(),{result}=await finished(s),storage=memory();const withScore=score=>({...result,canonical:{...result.canonical,score}});assert.equal(m.completeStackedDaily(s,withScore(500),storage).bestScore,500);assert.equal(m.completeStackedDaily(s,withScore(400),storage).gap,100);assert.equal(m.completeStackedDaily(s,withScore(500),storage).newBest,false);const improved=m.completeStackedDaily(s,withScore(700),storage);assert.equal(improved.newBest,true);assert.equal(improved.previousBest,500);assert.equal(m.readStackedDailyBest(storage,s),700);});
test('past-day completion keeps issuance day and build/season records remain distinct',async()=>{const m=await load(),s=await bound(),{result}=await finished(s),storage=memory();m.completeStackedDaily(s,result,storage);for(const changed of [{buildHash:'stacked-next'},{seasonId:'stacked-next-season'}])assert.equal(m.readStackedDailyBest(storage,{...s,...changed}),null);const parsed=JSON.parse(storage.getItem(m.STACKED_DAILY_STORAGE_KEY));assert.equal(parsed.records[0].dayKey,'2026-09-30');});
test('storage unavailable, malformed or oversized never blocks play or claims a save',async()=>{const m=await load(),s=await bound(),{result}=await finished(s);for(const storage of [null,{getItem(){throw Error('denied');},setItem(){throw Error('denied');}},{getItem:()=>'{bad',setItem(){throw Error('full');}}]){assert.equal(m.readStackedDailyBest(storage,s),null);assert.equal(m.completeStackedDaily(s,result,storage).saved,false);}for(const raw of ['null','{}','x'.repeat(65537),JSON.stringify({version:1,records:[{score:1e40}]})])assert.equal(m.readStackedDailyBest({getItem:()=>raw},s),null);});
test('bounded local history keeps latest 32 records across UTC dates',async()=>{const m=await load(),storage=memory();for(let i=0;i<35;i++){const s=m.bindStackedDailyChallenge(session(),{now:now+i*86400000}),{result}=await finished(s);m.completeStackedDaily(s,result,storage);}const saved=JSON.parse(storage.getItem(m.STACKED_DAILY_STORAGE_KEY));assert.equal(saved.records.length,32);assert.equal(saved.records[0].dayKey,'2026-11-03');assert.equal(m.readStackedDailyBest(storage,await bound()),null);});
test('an old paused daily finishing after 32 newer dates retains its promised best',async()=>{const m=await load(),storage=memory();for(let i=1;i<=32;i++){const s=m.bindStackedDailyChallenge(session(),{now:now+i*86400000}),{result}=await finished(s);m.completeStackedDaily(s,result,storage);}const s=await bound(),{result}=await finished(s),saved=m.completeStackedDaily(s,result,storage);assert.equal(saved.saved,true);assert.equal(m.readStackedDailyBest(storage,s),result.canonical.score);assert.equal(JSON.parse(storage.getItem(m.STACKED_DAILY_STORAGE_KEY)).records.length,32);});
test('duplicate stored identities or invalid records cannot supply a daily best',async()=>{const m=await load(),s=await bound(),{result}=await finished(s),storage=memory();m.completeStackedDaily(s,result,storage);const good=JSON.parse(storage.getItem(m.STACKED_DAILY_STORAGE_KEY));for(const records of [[...good.records,...good.records],[{...good.records[0],seed:1}],[{...good.records[0],score:-1}],[{...good.records[0],extra:'bad'}]]){storage.setItem(m.STACKED_DAILY_STORAGE_KEY,JSON.stringify({version:1,records}));assert.equal(m.readStackedDailyBest(storage,s),null);}});
