"""Append the authored clip library to the four hero pilot GLBs.

Pure Python, no Blender. The committed hero GLB (Blender's export of the nine
native clips) is the input; its geometry, textures, skin and native animations
are kept byte-for-byte and the library block is appended after them. Running
again first strips the previous library block recorded in ``asset.extras``.

Outputs (all under the approved pilot destination):
  apps/portal/assets/generated/hmh-actor-3d-pilot/<hero>.glb
  apps/portal/assets/generated/hmh-actor-3d-pilot/<hero>-clips.json
  apps/hmh-reboot/src/actor-3d-clip-table.mjs      (generated runtime clip table)
  docs/2.0/receipts/hmh-hero-clips-20260930/<hero>-clip-export.json
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/lib"))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from hmh_actor_pilot_paths import validate_pilot_output  # noqa: E402
import hmh_clip_library as library  # noqa: E402
import hmh_hero_clip_catalogue as catalogue  # noqa: E402

GENERATED = ROOT / "apps/portal/assets/generated/hmh-actor-3d-pilot"
RECEIPTS = ROOT / "docs/2.0/receipts/hmh-hero-clips-20260930"
TABLE = ROOT / "apps/hmh-reboot/src/actor-3d-clip-table.mjs"
GLB_LIMIT_BYTES = 9_000_000
# Runtime tick counts the shipped controller already uses for the nine native clips.
NATIVE_RUNTIME = {"idle": (60, True), "run": (60, True), "aim": (60, True), "pistol-fire": (12, False), "hurt": (12, False),
                  "dash": (18, False), "melee": (20, False), "grenade": (24, False), "death": (60, False)}
NATIVE_PROP = {"melee": "knife", "grenade": "frag", "death": "none"}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def native_entries():
    entries = []
    for name, (ticks, loop) in NATIVE_RUNTIME.items():
        entries.append({"name": name, "frames": ticks, "loop": loop, "blendIn": 0, "blendOut": 0, "interruptible": name in ("idle", "run", "aim"),
                        "prop": NATIVE_PROP.get(name, "blaster"), "category": "native", "samples": 25, "propReleaseTick": None})
    return entries


def write_runtime_table(manifests):
    shared = [c.manifest_entry() for c in catalogue.all_clips() if c.heroes is None]
    fidgets = {hero: catalogue.fidgets_for_hero(hero) for hero in catalogue.HEROES}
    fidget_entries = [c.manifest_entry() for c in catalogue.all_clips() if c.heroes is not None]
    rows = native_entries() + shared + fidget_entries
    lines = ["// GENERATED by scripts/hmh-blender/export-hmh-hero-clips.py from hmh_hero_clip_catalogue.py.",
             "// Presentation-only clip metadata for the hero GLBs: playback ticks at 60 Hz, loop flag,",
             "// blend ticks, interruptibility and which held prop the clip shows. Never simulation input.",
             "export const HERO_CLIP_TABLE = Object.freeze({"]
    for row in rows:
        release = "null" if row["propReleaseTick"] is None else str(row["propReleaseTick"])
        lines.append(f"  '{row['name']}': Object.freeze({{ frames: {row['frames']}, loop: {'true' if row['loop'] else 'false'}, blendIn: {row['blendIn']}, blendOut: {row['blendOut']}, "
                     f"interruptible: {'true' if row['interruptible'] else 'false'}, prop: '{row['prop']}', category: '{row['category']}', propReleaseTick: {release} }}),")
    lines.append("});")
    lines.append("export const HERO_FIDGET_CLIPS = Object.freeze({")
    for hero, names in fidgets.items():
        lines.append(f"  '{hero}': Object.freeze({json.dumps(names)}),")
    lines.append("});")
    lines.append("export const HERO_SHARED_LIBRARY_CLIPS = Object.freeze(" + json.dumps([c["name"] for c in shared]) + ");")
    lines.append("export const HERO_NATIVE_CLIPS = Object.freeze(" + json.dumps(list(NATIVE_RUNTIME)) + ");")
    lines.append("export const HERO_FIDGET_DELAY_TICKS = 240;")
    TABLE.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return rows


def export_hero(hero, dry_run=False):
    output = validate_pilot_output(ROOT, hero, "export", GENERATED / f"{hero}.glb")
    before = output.read_bytes()
    clips = catalogue.clips_for_hero(hero)
    result, report = library.inject_clips(before, clips)
    stripped_gltf, stripped_bin, previous = library.strip_library_block(*library.read_glb(before))
    native_bytes = len(before) if previous is None else len(library.write_glb(stripped_gltf, stripped_bin))
    gltf, _ = library.read_glb(result)
    joint_names = {gltf["nodes"][i]["name"] for i in gltf["skins"][0]["joints"]}
    unknown = sorted({bone for clip in clips for key in clip.keys for bone in key.pose if bone not in joint_names})
    manifest = {"schema": 1, "classification": "unapproved-runtime-character-pilot", "activeRuntimeIntegration": False, "actorId": hero,
                "file": f"{hero}.glb", "glbSha256": digest(result), "glbBytes": len(result), "nativeGlbBytes": native_bytes, "libraryBytes": len(result) - native_bytes,
                "clipDurationSeconds": library.CLIP_DURATION_SECONDS, "tickRate": library.TICK_RATE,
                "nativeClips": native_entries(), "libraryClips": report["libraryClips"], "fidgets": catalogue.fidgets_for_hero(hero),
                "ignoredBonesNotOnThisRig": unknown, "authoring": "scripts/hmh-blender/hmh_hero_clip_catalogue.py via hmh_clip_library.py",
                "rootMotion": False, "simulationAuthority": "none"}
    if len(result) > GLB_LIMIT_BYTES:
        raise RuntimeError(f"{hero}.glb would be {len(result)} bytes, over the {GLB_LIMIT_BYTES} limit")
    if not dry_run:
        output.write_bytes(result)
        (GENERATED / f"{hero}-clips.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
        RECEIPTS.mkdir(parents=True, exist_ok=True)
        receipt = {**manifest, "previousLibraryRecord": report["strippedPrevious"], "sha256Before": digest(before), "sha256After": manifest["glbSha256"]}
        (RECEIPTS / f"{hero}-clip-export.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({"hero": hero, "bytesBefore": len(before), "nativeBytes": native_bytes, "bytesAfter": len(result), "libraryClips": len(report["libraryClips"]),
                      "strippedPrevious": bool(report["strippedPrevious"]), "ignoredBones": unknown}))
    return manifest


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hero", action="append", choices=[*catalogue.HEROES, "all"], required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    heroes = list(catalogue.HEROES) if "all" in args.hero else args.hero
    manifests = {hero: export_hero(hero, args.dry_run) for hero in heroes}
    if not args.dry_run:
        write_runtime_table(manifests)
        print("HMH_HERO_CLIP_TABLE=" + str(TABLE))


if __name__ == "__main__":
    main()
