// The LitVM deployment the server reads addresses from (contract §8.1, A19).
//
// apps/portal/src/generated/litvm-addresses.mjs is generated by the contracts
// slice. Until it exists (or when it cannot be loaded), the server sees an
// 'unavailable' deployment with every address null, so chain-dependent
// endpoints fail closed instead of throwing.

const DEPLOYMENT_MODULE = '../apps/portal/src/generated/litvm-addresses.mjs';

export const UNAVAILABLE_DEPLOYMENT = Object.freeze({
  status: 'unavailable',
  chainId: 4441,
  startBlock: null,
  addresses: Object.freeze({
    gameRegistry: null,
    playerProfileRegistry: null,
    arcadeRankedEntry: null,
    scoreSubmissionRegistry: null,
    achievementRegistries: Object.freeze({ 'lester-blaster': null, chikun: null, stacked: null }),
  }),
});

let memo = null;

// importModule is injectable for tests only; production always uses the
// static specifier above so Vercel's file tracer bundles the module.
export async function loadDeployment({ importModule = null } = {}) {
  if (!importModule && memo) return memo;
  let deployment = UNAVAILABLE_DEPLOYMENT;
  try {
    const mod = importModule ? await importModule(DEPLOYMENT_MODULE) : await import('../apps/portal/src/generated/litvm-addresses.mjs');
    if (mod?.LITVM_DEPLOYMENT && typeof mod.LITVM_DEPLOYMENT === 'object') deployment = mod.LITVM_DEPLOYMENT;
  } catch {
    deployment = UNAVAILABLE_DEPLOYMENT;
  }
  if (!importModule) memo = deployment;
  return deployment;
}

export function isDeployed(deployment) {
  return deployment?.status === 'deployed';
}
