#!/usr/bin/env python
"""Build the runtime manifest for the HMH enemies wave (4-direction stills).

Reads the downloaded PNGs under apps/portal/assets/generated/hmh-enemies-wave/
and emits hmh-enemies-wave.mjs mapping each enemy id -> biome + directional
sprite paths. PixelLab "high top-down" 4-direction frame order is:
  00 = south (front), 01 = east (right), 02 = north (back), 03 = west (left).

Usage:
  python scripts/build-hmh-enemies-wave-manifest.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WAVE_DIR = ROOT / "apps/portal/assets/generated/hmh-enemies-wave"
LEDGER = WAVE_DIR / "enemies-ledger.json"
OUT = WAVE_DIR / "hmh-enemies-wave.mjs"

# Frame index -> direction for PixelLab high top-down 4-direction characters.
DIRECTION_ORDER = ["south", "east", "north", "west"]

# Display titles + suggested roguelike role hooks (kept descriptive, not wired
# to balance numbers here — the renderer just needs id/biome/sprites).
META = {
    "diamond-hands-whale": {"title": "Diamond Hands Whale", "archetype": "bruiser"},
    "influencer-shill": {"title": "Influencer Shill", "archetype": "caster"},
    "rug-pull-dev": {"title": "Rug-Pull Dev", "archetype": "saboteur"},
    "maxi-zealot": {"title": "Maxi Zealot", "archetype": "zealot"},
    "mempool-bot-runner": {"title": "Mempool Bot Runner", "archetype": "runner"},
    "taxman-validator": {"title": "Taxman Validator", "archetype": "enforcer"},
}


def main() -> None:
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    enemies = {}
    for eid, c in ledger.get("characters", {}).items():
        biome = c.get("biome")
        if not biome:
            continue
        rel_dir = f"./assets/generated/hmh-enemies-wave/{biome}"
        # Verify the 4 frames exist on disk before listing them.
        stills = {}
        for idx, direction in enumerate(DIRECTION_ORDER):
            png = WAVE_DIR / biome / f"{eid}-{idx:02d}.png"
            if png.exists():
                stills[direction] = f"{rel_dir}/{eid}-{idx:02d}.png"
        if len(stills) != 4:
            print(f"WARN {eid}: only {len(stills)}/4 frames present, skipping")
            continue
        meta = META.get(eid, {"title": eid, "archetype": "grunt"})
        enemies[eid] = {
            "id": eid,
            "title": meta["title"],
            "archetype": meta["archetype"],
            "biome": biome,
            "frameSize": [92, 92],
            "anchor": "bottom-center",
            "defaultDirection": "south",
            "stills": stills,
        }

    payload = {
        "source": "PixelLab generated HMH enemies wave (4-direction stills)",
        "directionOrder": DIRECTION_ORDER,
        "enemies": enemies,
    }
    body = json.dumps(payload, indent=2)
    OUT.write_text(
        "// AUTO-GENERATED by build-hmh-enemies-wave-manifest.py. Do not hand-edit.\n"
        "// 4-direction enemy stills (south/east/north/west) for the iso roguelike.\n"
        f"export const HMH_ENEMIES_WAVE = Object.freeze({body});\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} with {len(enemies)} enemies")


if __name__ == "__main__":
    main()
