"""Backdrop luminance profiles for the Chikun obstacle value separation.

    python scripts/build-chikun-obstacle-separation.py [--check]

The obstacle art separates from the scenery by value: an obstacle is graded
darker than the backdrop band it sits in (deepen) or lighter (lift, towards
the key light), whichever needs less change to reach the target contrast
(apps/chikun/src/obstacle-separation.mjs). The runtime cannot read back the
pixels behind an obstacle, so this script measures them offline: each region's
backdrop, composited exactly as the review plates do
(scripts/build-chikun-review-plates.py: shipped T1 layers, the runtime light
rig at the moments noon, golden hour, night and dawn are each alone in it:
chikun-rig-dump.mjs --pure), at eight scroll distances across
the 1280 px landscape view. For every 24 px row band the mean linear (WCAG)
luminance and its lower and upper quartiles (how dark or bright the backdrop
behind a flyer can get along the band) are written to
apps/chikun/src/obstacle-backdrop-profile.mjs as integers (luminance x 1000).
No obstacle, collision or course data is read.

--check exits non-zero when the generated module is not current.
"""
import argparse, importlib.util, json, subprocess, sys
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('plates', ROOT / 'scripts/build-chikun-review-plates.py')
plates = importlib.util.module_from_spec(spec); spec.loader.exec_module(plates)
OUT = ROOT / 'apps/chikun/src/obstacle-backdrop-profile.mjs'
BAND = 24
HEIGHT = 720
DISTANCES = [0, 900, 1900, 3000, 4200, 5500, 6900, 8400]


def profiles():
    cat = plates.catalog()
    R = json.loads(subprocess.run(['node', str(ROOT / 'scripts/chikun-blender/chikun-rig-dump.mjs'), '--pure'], capture_output=True, text=True, check=True, cwd=ROOT).stdout)
    nobody = np.zeros((1, 1, 4))
    out = {}
    for region in cat['regions']:
        layers, ground = plates.load_region(cat, region)
        out[region] = dict(mean=[], low=[], high=[])
        for key in plates.KEYS:
            rig = R[region][key]['landscape']
            lum = np.concatenate([plates.luminance(plates.plate(region, layers, ground, rig, float(D), 1280, [], nobody)[0][..., :3]) for D in DISTANCES], 1)
            bands = [lum[i:i + BAND].ravel() for i in range(0, HEIGHT, BAND)]
            out[region]['mean'].append([int(round(1000 * b.mean())) for b in bands])
            out[region]['low'].append([int(round(1000 * np.percentile(b, 25))) for b in bands])
            out[region]['high'].append([int(round(1000 * np.percentile(b, 75))) for b in bands])
    return out


def module(data):
    body = json.dumps(dict(band=BAND, keys=plates.KEYS, regions=data), separators=(',', ':'))
    return ('// Generated by scripts/build-chikun-obstacle-separation.py from the shipped scenery and the light rig. Do not edit.\n'
            '// Linear luminance x 1000 of each region\'s backdrop per 24 px row band at the four light keys: mean, lower and upper quartile.\n'
            f'export const BACKDROP_PROFILE = {body};\n'
            'Object.freeze(BACKDROP_PROFILE.keys);\n'
            'for (const r of Object.values(BACKDROP_PROFILE.regions)) { for (const s of Object.values(r)) { for (const row of s) Object.freeze(row); Object.freeze(s); } Object.freeze(r); }\n'
            'Object.freeze(BACKDROP_PROFILE.regions); Object.freeze(BACKDROP_PROFILE);\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    text = module(profiles())
    if a.check:
        current = OUT.read_text(encoding='utf8') if OUT.exists() else ''
        if current != text:
            print('obstacle-backdrop-profile.mjs is stale: run python scripts/build-chikun-obstacle-separation.py', file=sys.stderr)
            sys.exit(1)
        print('obstacle-backdrop-profile.mjs is current')
        return
    OUT.write_text(text, encoding='utf8', newline='\n')
    print('wrote', OUT.relative_to(ROOT).as_posix(), len(text), 'bytes')


if __name__ == '__main__':
    main()
