#!/usr/bin/env python3
"""Compile the Blueprint v5 data through the stable v3 compatibility module path."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BLUEPRINT_PATH = ROOT / "docs" / "game-design" / "data" / "hmh-level-1-world-blueprint-v3.json"
OUTPUT_PATH = ROOT / "apps" / "portal" / "src" / "hmh-level-one-world-v3-runtime.mjs"

MATERIAL_KEYS = {
    "g": "world-v3-material/dry-grass",
    "G": "world-v3-material/lush-grass",
    "F": "world-v3-material/forest-floor",
    "D": "world-v3-material/packed-dirt",
    "S": "world-v3-material/wasteland-sand",
    "R": "world-v3-material/rocky-ground",
    "X": "world-v3-material/cliff-mountain",
    "C": "world-v3-material/cobblestone",
    "A": "world-v3-material/cracked-asphalt",
    "f": "world-v3-material/farm-field",
    "B": "world-v3-material/beach-sand",
    "M": "world-v3-material/mud-reeds",
    "W": "world-v3-material/fresh-deep-water",
    "w": "world-v3-material/shallow-ford",
    "O": "world-v3-material/sea-water",
    "H": "world-v3-material/wood-bridge",
    "Q": "world-v3-material/stone-road-bridge",
}

ROLE_BY_CODE = {
    "g": "grass", "G": "grass", "F": "grass", "D": "dirt", "S": "sand",
    "R": "rocky", "X": "rocky", "C": "road", "A": "road", "f": "grass",
    "B": "shore", "M": "shore", "W": "water", "w": "water", "O": "water",
    "H": "bridge", "Q": "bridge",
}


def runtime_payload(blueprint: dict) -> dict:
    terrain_families = []
    for family in blueprint["artGrammar"]["terrainFamilies"]:
        terrain_families.append({
            **family,
            "role": ROLE_BY_CODE[family["code"]],
            "materialKey": MATERIAL_KEYS[family["code"]],
        })
    return {
        "id": blueprint["id"],
        "version": blueprint["version"],
        "status": "approved-live-runtime",
        "levelId": blueprint["levelId"],
        "dimensions": blueprint["dimensions"],
        "projection": blueprint["projection"],
        "anchors": blueprint["anchors"],
        "criticalPath": blueprint["criticalPath"],
        "routePresentation": blueprint["routePresentation"],
        "pointsOfInterest": blueprint["pointsOfInterest"],
        "bridges": blueprint["hydrology"]["bridges"],
        "terrainFamilies": terrain_families,
        "layers": {name: value["rows"] for name, value in blueprint["layers"].items()},
        "metrics": blueprint["metrics"],
    }


RUNTIME_SOURCE = r'''
// Generated by scripts/build-hmh-level-one-world-v3-runtime.py. Do not hand edit.
const deepFreeze = (value) => {
  if (!value || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
};

const DATA = __PAYLOAD__;
export const HMH_LEVEL_ONE_WORLD_V3 = deepFreeze(DATA);

const WIDTH = DATA.dimensions.width;
const HEIGHT = DATA.dimensions.height;
const SPAWN_X = DATA.anchors.spawn.x;
const SPAWN_Y = DATA.anchors.spawn.y;
const TERRAIN_BY_CODE = new Map(DATA.terrainFamilies.map((family) => [family.code, family]));
const CARDINAL = Object.freeze([
  Object.freeze({ name: 'north', dx: 0, dy: -1, bit: 1, opposite: 4 }),
  Object.freeze({ name: 'east', dx: 1, dy: 0, bit: 2, opposite: 8 }),
  Object.freeze({ name: 'south', dx: 0, dy: 1, bit: 4, opposite: 1 }),
  Object.freeze({ name: 'west', dx: -1, dy: 0, bit: 8, opposite: 2 }),
]);

function authoredInBounds(x, y) {
  return x >= 0 && x < WIDTH && y >= 0 && y < HEIGHT;
}

function rawCellAtAuthored(x, y) {
  if (!authoredInBounds(x, y)) {
    return { terrain: 'X', biome: 'M', elevation: '3', groundNav: '#', route: '.', encounter: '.' };
  }
  return {
    terrain: DATA.layers.terrain[y][x],
    biome: DATA.layers.biome[y][x],
    elevation: DATA.layers.elevation[y][x],
    groundNav: DATA.layers.groundNav[y][x],
    route: DATA.layers.route[y][x],
    encounter: DATA.layers.encounter[y][x],
  };
}

export function authoredCellToWorld(authoredX, authoredY) {
  return Object.freeze({ x: Math.round(Number(authoredX) || 0) - SPAWN_X, y: Math.round(Number(authoredY) || 0) - SPAWN_Y });
}

export function worldToAuthoredCell(worldX, worldY) {
  const x = Math.round(Number(worldX) || 0) + SPAWN_X;
  const y = Math.round(Number(worldY) || 0) + SPAWN_Y;
  return Object.freeze({ x, y, inBounds: authoredInBounds(x, y) });
}

export function levelOneWorldV3BridgeCrossing(bridgeId) {
  const bridge = DATA.bridges.find((item) => item.id === bridgeId);
  if (!bridge) return null;
  return Object.freeze({
    ...bridge,
    entryWorld: authoredCellToWorld(bridge.entry[0], bridge.entry[1]),
    exitWorld: authoredCellToWorld(bridge.exit[0], bridge.exit[1]),
  });
}

export function levelOneWorldV3WorldBounds() {
  return Object.freeze({ minX: -SPAWN_X, maxX: WIDTH - 1 - SPAWN_X, minY: -SPAWN_Y, maxY: HEIGHT - 1 - SPAWN_Y, width: WIDTH, height: HEIGHT });
}

export function levelOneWorldV3ElevationAt(worldX = 0, worldY = 0) {
  const x = Math.round(Number(worldX) || 0) + SPAWN_X;
  const y = Math.round(Number(worldY) || 0) + SPAWN_Y;
  if (!authoredInBounds(x, y)) return 3;
  return Math.max(0, Math.min(3, DATA.layers.elevation[y].charCodeAt(x) - 48));
}

export function levelOneWorldV3CellAt(worldX = 0, worldY = 0) {
  const authored = worldToAuthoredCell(worldX, worldY);
  const raw = rawCellAtAuthored(authored.x, authored.y);
  const family = TERRAIN_BY_CODE.get(raw.terrain) ?? TERRAIN_BY_CODE.get('X');
  return Object.freeze({
    worldX: Math.round(Number(worldX) || 0),
    worldY: Math.round(Number(worldY) || 0),
    authoredX: authored.x,
    authoredY: authored.y,
    inBounds: authored.inBounds,
    ...raw,
    terrainId: family.id,
    terrainRole: family.role,
    materialKey: family.materialKey,
    blocked: raw.groundNav === '#',
    slow: raw.groundNav === '~',
    isBridge: raw.terrain === 'H' || raw.terrain === 'Q',
    isWater: raw.terrain === 'W' || raw.terrain === 'w' || raw.terrain === 'O',
  });
}

export function levelOneWorldV3NeighborMask(worldX = 0, worldY = 0) {
  const cell = levelOneWorldV3CellAt(worldX, worldY);
  let sameTerrainMask = 0;
  let walkableMask = 0;
  const neighbors = {};
  for (const direction of CARDINAL) {
    const neighbor = levelOneWorldV3CellAt(cell.worldX + direction.dx, cell.worldY + direction.dy);
    if (neighbor.terrain === cell.terrain) sameTerrainMask |= direction.bit;
    if (!cell.blocked && !neighbor.blocked) walkableMask |= direction.bit;
    neighbors[direction.name] = Object.freeze({
      terrain: neighbor.terrain,
      groundNav: neighbor.groundNav,
      inBounds: neighbor.inBounds,
    });
  }
  return Object.freeze({ sameTerrainMask, walkableMask, neighbors: Object.freeze(neighbors) });
}

function reachableAuthoredCells() {
  const start = DATA.anchors.spawn;
  const key = (x, y) => `${x}|${y}`;
  const queue = [[start.x, start.y]];
  const visited = new Set([key(start.x, start.y)]);
  for (let cursor = 0; cursor < queue.length; cursor += 1) {
    const [x, y] = queue[cursor];
    for (const direction of CARDINAL) {
      const nx = x + direction.dx;
      const ny = y + direction.dy;
      const nextKey = key(nx, ny);
      if (!authoredInBounds(nx, ny) || visited.has(nextKey) || rawCellAtAuthored(nx, ny).groundNav === '#') continue;
      visited.add(nextKey);
      queue.push([nx, ny]);
    }
  }
  return visited;
}

export function buildLevelOneWorldV3Reachability() {
  const visited = reachableAuthoredCells();
  const key = (x, y) => `${x}|${y}`;
  let totalPassable = 0;
  for (let y = 0; y < HEIGHT; y += 1) {
    for (let x = 0; x < WIDTH; x += 1) if (rawCellAtAuthored(x, y).groundNav !== '#') totalPassable += 1;
  }
  const anchors = (items) => Object.freeze(items.map((item) => Object.freeze({ id: item.id, x: item.x, y: item.y, reachable: visited.has(key(item.x, item.y)) })));
  const bridges = Object.freeze(DATA.bridges.map((bridge) => {
    const north = rawCellAtAuthored(bridge.x, bridge.y - 1).groundNav !== '#';
    const east = rawCellAtAuthored(bridge.x + 1, bridge.y).groundNav !== '#';
    const south = rawCellAtAuthored(bridge.x, bridge.y + 1).groundNav !== '#';
    const west = rawCellAtAuthored(bridge.x - 1, bridge.y).groundNav !== '#';
    return Object.freeze({ ...bridge, reachable: visited.has(key(bridge.x, bridge.y)), connectsWalkableSides: (north && south) || (east && west) });
  }));
  return Object.freeze({
    reachableGroundCells: visited.size,
    totalPassableCells: totalPassable,
    unreachablePassableCells: totalPassable - visited.size,
    criticalPath: anchors(DATA.criticalPath),
    pointsOfInterest: anchors(DATA.pointsOfInterest),
    bridges,
  });
}
'''


def main() -> None:
    blueprint = json.loads(BLUEPRINT_PATH.read_text(encoding="utf-8"))
    payload = json.dumps(runtime_payload(blueprint), separators=(",", ":"), ensure_ascii=False)
    source = RUNTIME_SOURCE.replace("__PAYLOAD__", payload).lstrip()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(source, encoding="utf-8")
    print(json.dumps({"runtimeModule": str(OUTPUT_PATH), "bytes": len(source.encode("utf-8"))}, indent=2))


if __name__ == "__main__":
    main()
