#!/usr/bin/env python
"""Consolidate fragmented 8-direction PixelLab animations into a clean runtime manifest.

PixelLab returns each *direction* of a logical animation as a separate animation
UUID that often carries the SAME label (e.g. "walk", "walk", "walk"...). The
harvest script names animations positionally and de-dupes repeated labels with a
numeric suffix, so one logical 8-direction "walk" gets fragmented into
`walk`, `walk-2`, `walk-3`, ... `walk-8`, each holding a single direction. The
renderer looks up `animations[name][direction]`, so it only ever finds one
facing under the base name and every other facing falls back to a mirrored
single direction. The result: heroes/enemies never face most directions.

This script reads the on-disk ledger (roster-ledger.json) and CONSOLIDATES
those fragmented variants back into a single animation per base name with all
available directions merged. Rules:

  * Base name is the label with any trailing `-N` or `-8dir`/`-8dir-N` stripped.
    e.g. walk, walk-2..8 -> walk ; idle-8dir, idle-8dir-2..8 -> idle ;
    death-8dir -> death.
  * For each base, merge every variant's direction map. If two variants both
    provide the SAME direction, the one with MORE frames wins (junk single-frame
    or short duplicates lose to the real set).
  * Output preserves the harvest manifest shape exactly:
      { <key>: { role, character_id, animations: { <name>: { <dir>: [paths] } } } }

Pure on-disk transform: no network, no PixelLab calls. Safe + deterministic.

Usage:
  python scripts/consolidate-hmh-roster-directions.py report   # show before/after coverage, no write
  python scripts/consolidate-hmh-roster-directions.py build    # write consolidated manifest
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT_ROOT = ROOT / "apps/portal/assets/generated/hmh-animated-roster"
LEDGER = OUT_ROOT / "roster-ledger.json"
MANIFEST = OUT_ROOT / "hmh-animated-roster.mjs"

DIRECTIONS = ["south", "south-east", "east", "north-east", "north", "north-west", "west", "south-west"]

# Strip a trailing -8dir / -8dir-N / -N variant suffix to find the logical base.
_SUFFIX_RE = re.compile(r"(?:-8dir)?(?:-\d+)?$")


def base_name(name: str) -> str:
    """walk-3 -> walk ; idle-8dir-5 -> idle ; death-8dir -> death ; attack -> attack."""
    # Remove an -8dir token anywhere it appears, then a trailing -N.
    n = name.replace("-8dir", "")
    n = re.sub(r"-\d+$", "", n)
    return n or name


def consolidate_character(entry: dict[str, Any]) -> dict[str, Any]:
    anims = entry.get("animations", {})
    merged: dict[str, dict[str, list[str]]] = {}
    for anim_name, dirs in anims.items():
        base = base_name(anim_name)
        bucket = merged.setdefault(base, {})
        for direction, frames in dirs.items():
            if direction not in DIRECTIONS:
                continue
            existing = bucket.get(direction)
            # Keep the richer frame set when a direction appears more than once.
            if existing is None or len(frames) > len(existing):
                bucket[direction] = list(frames)
    out = {k: v for k, v in entry.items() if k != "animations"}
    out["animations"] = merged
    return out


def consolidate_all(ledger: dict[str, Any]) -> dict[str, Any]:
    return {key: consolidate_character(entry) for key, entry in ledger.items()}


def coverage(ledger: dict[str, Any]) -> dict[str, dict[str, int]]:
    cov: dict[str, dict[str, int]] = {}
    for key, entry in ledger.items():
        cov[key] = {an: len(dirs) for an, dirs in entry.get("animations", {}).items()}
    return cov


def cmd_report() -> None:
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    before = coverage(ledger)
    after = coverage(consolidate_all(ledger))
    for key in sorted(ledger):
        b = before.get(key, {})
        a = after.get(key, {})
        print(f"\n### {key}  ({len(b)} raw anims -> {len(a)} consolidated)")
        for an in sorted(a):
            dirs = a[an]
            flag = "OK-8dir" if dirs >= 8 else ("partial" if dirs >= 2 else "single")
            print(f"  {an:18s} {dirs} dirs  [{flag}]")


def build_manifest(consolidated: dict[str, Any]) -> None:
    body = json.dumps(consolidated, indent=2)
    MANIFEST.write_text(
        "// AUTO-GENERATED by pixellab-hmh-harvest-animated-roster.py + consolidate-hmh-roster-directions.py. Do not hand-edit.\n"
        "// 8-direction animated character roster (heroes/enemies/bosses).\n"
        "// Fragmented per-direction PixelLab animations are consolidated into one\n"
        "// animation per base name with all directions merged (see consolidate script).\n"
        "// Shape: { <key>: { role, character_id, animations: { <name>: { <direction>: [framePaths] } } } }\n"
        f"export const HMH_ANIMATED_ROSTER = Object.freeze({body});\n",
        encoding="utf-8",
    )
    print(f"wrote {MANIFEST.relative_to(ROOT)} with {len(consolidated)} characters")


def cmd_build() -> None:
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    consolidated = consolidate_all(ledger)
    build_manifest(consolidated)
    # quick summary
    eight = sum(1 for e in consolidated.values()
                for d in e.get("animations", {}).values() if len(d) >= 8)
    print(f"consolidated animations with full 8-dir coverage: {eight}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["report", "build"])
    args = ap.parse_args()
    if args.command == "report":
        cmd_report()
    else:
        cmd_build()


if __name__ == "__main__":
    main()
