"""Derived low-download tier. Preserves every non-image buffer view verbatim."""
import gzip
import hashlib
import io
import json
import struct
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "apps/portal/assets/generated/hmh-actor-3d-pilot"
TARGET = SOURCE / "low"
HEROES = ("lit-commando", "lilly", "lit-valkyrie", "lester-original")
CAP = 1_500_000

def derive(source_bytes, base_edge):
    json_length = struct.unpack_from("<I", source_bytes, 12)[0]
    doc = json.loads(source_bytes[20:20+json_length])
    binary = source_bytes[28+json_length:]
    base = set()
    for material in doc["materials"]:
        texture = material.get("pbrMetallicRoughness", {}).get("baseColorTexture")
        if texture:
            base.add(doc["textures"][texture["index"]]["source"])
    encoded, ledger = {}, []
    for index, row in enumerate(doc["images"]):
        view = doc["bufferViews"][row["bufferView"]]
        start = view.get("byteOffset", 0)
        image = Image.open(io.BytesIO(binary[start:start+view["byteLength"]])).convert("RGBA")
        source_size = list(image.size)
        edge = base_edge if index in base else 128
        image.thumbnail((edge, edge), Image.Resampling.LANCZOS)
        output = io.BytesIO()
        image.save(output, format="WEBP", quality=90 if index in base else 95, method=4, exact=True)
        encoded[row["bufferView"]] = output.getvalue()
        row["mimeType"] = "image/webp"
        ledger.append({"index": index, "role": "base" if index in base else "normal-or-material",
                       "sourceSize": source_size, "size": list(image.size), "bytes": len(output.getvalue())})
    for texture in doc["textures"]:
        image = texture.pop("source")
        texture.setdefault("extensions", {})["EXT_texture_webp"] = {"source": image}
    doc["extensionsUsed"] = ["EXT_texture_webp"]
    doc["extensionsRequired"] = ["EXT_texture_webp"]
    parts, offset = [], 0
    for index, view in enumerate(doc["bufferViews"]):
        start = view.get("byteOffset", 0)
        data = encoded.get(index, binary[start:start+view["byteLength"]])
        view["byteOffset"], view["byteLength"] = offset, len(data)
        parts.append(data + b"\0" * (-len(data) % 4))
        offset += len(parts[-1])
    payload = b"".join(parts)
    doc["buffers"][0]["byteLength"] = len(payload)
    text = json.dumps(doc, separators=(",", ":")).encode()
    text += b" " * (-len(text) % 4)
    glb = (struct.pack("<III", 0x46546C67, 2, 28+len(text)+len(payload))
           + struct.pack("<II", len(text), 0x4E4F534A) + text
           + struct.pack("<II", len(payload), 0x004E4942) + payload)
    return glb, gzip.compress(glb, compresslevel=9, mtime=0), ledger

def main():
    TARGET.mkdir(exist_ok=True)
    existing = TARGET / "manifest.json"
    if existing.exists() and json.loads(existing.read_text()).get("geometryChanged"):
        raise RuntimeError("A mesh LOD is active. Rebuild with optimize-hmh-actor-mesh-tier.py; do not replace it with texture-only geometry.")
    entries = {}
    for hero in HEROES:
        source_bytes = (SOURCE / (hero + ".glb")).read_bytes()
        for edge in (512, 480, 448, 416, 384):
            glb, packed, images = derive(source_bytes, edge)
            if len(packed) <= CAP:
                break
        if len(packed) > CAP:
            raise RuntimeError(f"{hero}: no accepted tier meets {CAP} bytes")
        file = hero + ".glb.gz"
        (TARGET / file).write_bytes(packed)
        entries[hero] = {"file": file, "compressedBytes": len(packed), "glbBytes": len(glb),
                         "sourceBytes": len(source_bytes), "sourceSha256": hashlib.sha256(source_bytes).hexdigest(),
                         "sha256": hashlib.sha256(packed).hexdigest(), "glbSha256": hashlib.sha256(glb).hexdigest(),
                         "baseEdge": edge, "materialEdge": 128, "images": images}
        print(json.dumps({"hero": hero, "bytes": len(packed), "baseEdge": edge}))
    manifest = {"schema": 1, "kind": "derived-low-download-texture-tier", "geometryChanged": False,
                "rigChanged": False, "animationChanged": False, "paidGeneration": False, "actors": entries}
    (TARGET / "manifest.json").write_text(json.dumps(manifest, indent=2)+"\n", encoding="utf-8")
    minimal = {hero: {key: row[key] for key in ("file", "compressedBytes", "glbBytes")} for hero, row in entries.items()}
    registry = "// GENERATED by scripts/optimize-hmh-actor-texture-tier.py. Lazy presentation chunk only.\n"
    registry += "export const ACTOR3D_LOW_ASSETS = Object.freeze(" + json.dumps(minimal, separators=(",", ":")) + ");\n"
    (ROOT / "apps/hmh-reboot/src/actor-3d-texture-tiers.mjs").write_text(registry, encoding="utf-8")

if __name__ == "__main__":
    main()
