#!/usr/bin/env python
"""Resumable PixelLab generator: weapon VFX + power-up icons for Hard Money Heroes.

Fast path only (`create_map_object`, ~1 generation each) for the non-character
asset families the game is short on or rendering as fallbacks:
  - weapon muzzle / projectile / impact VFX (incl. throwing axe + grenade arc/blast)
  - power-up pickup icons (existing 9 + new roguelike power-ups)

Humanoid enemy CHARACTERS are generated by a separate script
(pixellab-hmh-enemies-wave.py) because they use the multi-step character API.

Auth read from ~/.claude.json; never logged/committed.

Usage:
  python scripts/pixellab-hmh-fx-powerups-wave.py queue   [--limit N]
  python scripts/pixellab-hmh-fx-powerups-wave.py collect [--limit N]
  python scripts/pixellab-hmh-fx-powerups-wave.py status
"""
from __future__ import annotations

import argparse
import asyncio
import json
import re
import time
import urllib.request
from pathlib import Path
from typing import Any

from mcp import ClientSession
from mcp.client.streamable_http import streamablehttp_client

ROOT = Path(__file__).resolve().parents[1]
PUBLIC_ROOT = Path("apps/portal/assets/generated/hmh-fx-powerups-wave")
OUT_ROOT = ROOT / PUBLIC_ROOT
LEDGER = OUT_ROOT / "fx-powerups-ledger.json"
UUID_RE = re.compile(r"[0-9a-fA-F-]{36}")
URL_RE = re.compile(r"https?://[^\s,)\]>'\"]+")

NO_TEXT = "no words, no letters, no numbers, no labels, no logos, no watermark"
FX_STYLE = (
    "centered pixel-art game VFX sprite on fully transparent background, retro "
    "80s/90s arcade, bright additive glow, limited SNES/Neo-Geo palette, "
    "Litecoin silver-and-blue accent, crisp clean edges; " + NO_TEXT
)
ICON_STYLE = (
    "centered pixel-art game pickup item icon on fully transparent background, "
    "retro arcade collectible, readable silhouette, soft glow, limited "
    "SNES/Neo-Geo palette, Litecoin silver-and-blue accent; " + NO_TEXT
)


def fx(slug: str, desc: str, size: int = 96) -> dict[str, Any]:
    return {
        "job_key": slug, "category": "vfx", "tool": "create_map_object",
        "args": {"description": f"{desc}; {FX_STYLE}", "width": size, "height": size,
                 "view": "high top-down", "outline": "lineless", "shading": "detailed shading"},
    }


def icon(slug: str, desc: str, size: int = 96) -> dict[str, Any]:
    return {
        "job_key": slug, "category": "powerup", "tool": "create_map_object",
        "args": {"description": f"{desc}; {ICON_STYLE}", "width": size, "height": size,
                 "view": "high top-down", "outline": "single color outline", "shading": "detailed shading"},
    }


def all_specs() -> list[dict[str, Any]]:
    s: list[dict[str, Any]] = []
    # --- Weapon VFX ---
    vfx = [
        ("muzzle-settler", "small crisp blue-white pistol muzzle flash burst, star shape"),
        ("muzzle-shotgun", "wide orange shotgun blast cone flash"),
        ("muzzle-auto", "rapid silver-blue minigun muzzle flash with energy coil"),
        ("muzzle-rail", "thin charged white-cyan rail beam streak, horizontal"),
        ("muzzle-oracle", "huge purple-white dragon energy beam charge burst"),
        ("tracer-silver", "small silver bullet tracer streak"),
        ("tracer-cyan", "cyan energy projectile bolt"),
        ("tracer-purple", "purple heavy oracle bolt with trail"),
        ("axe-spin", "silver throwing hatchet with Litecoin-blue handle, motion spin blur"),
        ("axe-stick-impact", "silver axe-hit impact sparks burst"),
        ("grenade-bomb", "matte-black round bomb with lit fuse spark, side view"),
        ("grenade-arc-trail", "blue-white arcing throw motion trail dots"),
        ("grenade-blast", "big blue-white explosion blast flash ring"),
        ("melee-slash", "clean silver curved sword arc slash trail"),
        ("impact-spark", "bright silver impact spark hit burst"),
        ("crit-burst", "yellow-white critical hit star burst"),
        ("enemy-death-puff", "grey-red smoke death puff dissipating"),
        ("shockwave-ring", "expanding cyan shockwave ring"),
    ]
    for slug, d in vfx:
        s.append(fx(slug, d))
    # --- Power-up icons (existing library + new roguelike pickups) ---
    pickups = [
        ("health-pack", "glowing blue hardware-wallet medkit with white heartbeat cross"),
        ("grenade-crate", "matte-black bomb cache crate with small blue accent"),
        ("bonus-life", "tiny heroic head icon with silver-blue halo, 1-up style"),
        ("spread-ltc-chip", "cyan fan-shaped weapon chip emitting arcs"),
        ("hash-rail-core", "glowing white-cyan energy core cylinder"),
        ("score-multiplier", "gold 2x multiplier token coin with blue rim"),
        ("shield-cache", "hovering blue-silver hexagon barrier shield device"),
        ("ammo-cache", "silver ammo magazine crate with orange hazard stripe"),
        ("ltc-cache", "small sparkling silver coin pile pickup"),
        # NEW roguelike power-ups:
        ("magnet-surge", "glowing horseshoe magnet pickup with blue pull rings, pulls loot"),
        ("time-dilation", "blue hourglass with slow-motion swirl, bullet-time pickup"),
        ("berserk-candle", "red-and-green flaming candlestick chart pickup, rage buff"),
        ("orbital-wallet", "small silver satellite wallet orb that orbits, pickup"),
        ("nuke-liquidation", "red glowing screen-clear bomb pickup, danger nuke"),
        ("reroll-token", "blue circular-arrow reroll token coin pickup"),
    ]
    for slug, d in pickups:
        s.append(icon(slug, d))
    return s


def load_ledger() -> dict[str, Any]:
    if LEDGER.exists():
        return json.loads(LEDGER.read_text(encoding="utf-8"))
    return {"jobs": []}


def save_ledger(data: dict[str, Any]) -> None:
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    LEDGER.write_text(json.dumps(data, indent=2), encoding="utf-8")


def load_server() -> dict[str, Any]:
    d = json.loads((Path.home() / ".claude.json").read_text(encoding="utf-8"))
    for proj in d.get("projects", {}).values():
        srv = proj.get("mcpServers", {}).get("pixellab")
        if srv:
            return srv
    raise SystemExit("no pixellab MCP server in ~/.claude.json")


def result_text(result: Any) -> str:
    return "\n".join(c.text for c in getattr(result, "content", []) or [] if hasattr(c, "text"))


async def queue(limit: int | None) -> None:
    data = load_ledger()
    existing = {j["job_key"]: j for j in data["jobs"]}
    specs = all_specs()
    server = load_server()
    queued = 0
    async with streamablehttp_client(server["url"], headers=server.get("headers", {})) as (r, w, _):
        async with ClientSession(r, w) as sess:
            await sess.initialize()
            for sp in specs:
                if sp["job_key"] in existing and existing[sp["job_key"]].get("object_id"):
                    continue
                if limit is not None and queued >= limit:
                    break
                try:
                    res = await sess.call_tool(sp["tool"], sp["args"])
                    text = result_text(res)
                    m = UUID_RE.search(text)
                    existing[sp["job_key"]] = {
                        "job_key": sp["job_key"], "category": sp["category"],
                        "object_id": m.group(0) if m else None, "status": "queued", "raw": text[:160]}
                    queued += 1
                    print(f"queued {sp['job_key']} -> {existing[sp['job_key']]['object_id']}", flush=True)
                    time.sleep(1.0)
                except Exception as exc:
                    print(f"ERR queue {sp['job_key']}: {exc}", flush=True)
                    time.sleep(3.0)
            data["jobs"] = list(existing.values())
            save_ledger(data)
    print(json.dumps({"queued_now": queued,
                      "have_ids": sum(1 for j in existing.values() if j.get("object_id")),
                      "total_specs": len(specs)}, indent=2))


def download(url: str, dest: Path) -> bool:
    try:
        dest.parent.mkdir(parents=True, exist_ok=True)
        req = urllib.request.Request(url, headers={"User-Agent": "hmh-fx-powerups"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            dest.write_bytes(resp.read())
        return dest.stat().st_size > 0
    except Exception as exc:
        print(f"  download err: {exc}", flush=True)
        return False


async def collect(limit: int | None) -> None:
    data = load_ledger()
    server = load_server()
    done = 0
    async with streamablehttp_client(server["url"], headers=server.get("headers", {})) as (r, w, _):
        async with ClientSession(r, w) as sess:
            await sess.initialize()
            for job in data["jobs"]:
                if job.get("status") == "complete" or not job.get("object_id"):
                    continue
                if limit is not None and done >= limit:
                    break
                try:
                    res = await sess.call_tool("get_map_object", {"object_id": job["object_id"]})
                    text = result_text(res)
                    urls = URL_RE.findall(text)
                    png = next((u for u in urls if ".png" in u.lower()), urls[0] if urls else None)
                    if "processing" in text.lower() or not png:
                        job["status"] = "processing"
                        print(f"  {job['job_key']}: processing", flush=True)
                        continue
                    dest = OUT_ROOT / job["category"] / f"{job['job_key']}.png"
                    if download(png, dest):
                        job["status"] = "complete"
                        job["src"] = f"./assets/generated/hmh-fx-powerups-wave/{job['category']}/{job['job_key']}.png"
                        done += 1
                        print(f"  saved {job['job_key']}", flush=True)
                except Exception as exc:
                    print(f"  ERR collect {job['job_key']}: {exc}", flush=True)
                time.sleep(0.6)
    save_ledger(data)
    by_status: dict[str, int] = {}
    for j in data["jobs"]:
        by_status[j.get("status", "?")] = by_status.get(j.get("status", "?"), 0) + 1
    print(json.dumps({"collected_now": done, "by_status": by_status}, indent=2))


def status() -> None:
    data = load_ledger()
    by_status: dict[str, int] = {}
    for j in data["jobs"]:
        by_status[j.get("status", "?")] = by_status.get(j.get("status", "?"), 0) + 1
    print(json.dumps({"total_specs": len(all_specs()), "ledger_jobs": len(data["jobs"]),
                      "by_status": by_status}, indent=2))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["queue", "collect", "status"])
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args()
    if args.command == "queue":
        asyncio.run(queue(args.limit))
    elif args.command == "collect":
        asyncio.run(collect(args.limit))
    else:
        status()


if __name__ == "__main__":
    main()
