#!/usr/bin/env python3
"""Promote complete PixelLab AAA wave actor kits into the runtime HMH animated roster.

Only actors with every required state and all 8 directions are promoted. Partial
kits remain in the AAA candidate folder and are not wired live.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PORTAL = ROOT / "apps/portal"
AAA_ROOT = PORTAL / "assets/generated/hmh-aaa-pixellab-quality-wave/actors"
AAA_LEDGER = PORTAL / "assets/generated/hmh-aaa-pixellab-quality-wave/aaa-quality-wave-ledger.json"
ROSTER_ROOT = PORTAL / "assets/generated/hmh-animated-roster"
ROSTER_LEDGER = ROSTER_ROOT / "roster-ledger.json"
ROSTER_MANIFEST = ROSTER_ROOT / "hmh-animated-roster.mjs"

DIRECTIONS = ["south", "south-east", "east", "north-east", "north", "north-west", "west", "south-west"]
STATES = ["idle", "walk", "run", "attack-tell", "attack", "hit", "death", "spawn-in"]
QUALITY = "AAA isometric pixel-art replacement inspired by Hades / Dead Cells / AoE2-DE readability; human/undead-readable Level 1 enemy silhouette"
SOURCE = "pixellab-aaa-quality-wave-v2"


def portal_rel(path: Path) -> str:
    return "./" + path.relative_to(PORTAL).as_posix()


def assert_complete(actor: str) -> None:
    missing: list[str] = []
    for state in STATES:
        for direction in DIRECTIONS:
            if not any((AAA_ROOT / actor / state / direction).glob("*.png")):
                missing.append(f"{state}/{direction}")
    if missing:
        raise SystemExit(f"{actor} is not complete; missing {len(missing)} slots: {', '.join(missing[:16])}")


def actor_character_id(actor: str) -> str:
    ledger = json.loads(AAA_LEDGER.read_text(encoding="utf-8"))
    return ledger.get("targets", {}).get(actor, {}).get("character_id", f"{SOURCE}:{actor}")


def copy_actor(actor: str) -> dict:
    assert_complete(actor)
    dst_actor = ROSTER_ROOT / actor
    if dst_actor.exists():
        shutil.rmtree(dst_actor)
    animations: dict[str, dict[str, list[str]]] = {}
    for state in STATES:
        animations[state] = {}
        for direction in DIRECTIONS:
            src_dir = AAA_ROOT / actor / state / direction
            dst_dir = dst_actor / state / direction
            dst_dir.mkdir(parents=True, exist_ok=True)
            frame_paths = []
            for src in sorted(src_dir.glob("*.png")):
                dst = dst_dir / src.name
                shutil.copy2(src, dst)
                frame_paths.append(portal_rel(dst))
            animations[state][direction] = frame_paths
    return {
        "role": "enemy",
        "character_id": actor_character_id(actor),
        "source": SOURCE,
        "quality_target": QUALITY,
        "replaces": "old partial runtime enemy kit",
        "animations": animations,
    }


def write_manifest(roster: dict) -> None:
    body = json.dumps(roster, indent=2)
    ROSTER_MANIFEST.write_text(
        "// AUTO-GENERATED by promote-hmh-aaa-wave-to-roster.py. Do not hand-edit.\n"
        "// 8-direction animated character roster (heroes/enemies/bosses).\n"
        "// Shape: { <key>: { role, character_id, animations: { <name>: { <direction>: [framePaths] } } } }\n"
        f"export const HMH_ANIMATED_ROSTER = Object.freeze({body});\n\n"
        "export default HMH_ANIMATED_ROSTER;\n",
        encoding="utf-8",
    )


def main() -> None:
    actors = [arg for arg in __import__('sys').argv[1:] if arg]
    if not actors:
        actors = ["trench-degen", "phishing-angler"]
    roster = json.loads(ROSTER_LEDGER.read_text(encoding="utf-8"))
    promoted = []
    for actor in actors:
        roster[actor] = copy_actor(actor)
        promoted.append(actor)
    ROSTER_LEDGER.write_text(json.dumps(roster, indent=2) + "\n", encoding="utf-8")
    write_manifest(roster)
    print(json.dumps({"promoted": promoted, "source": SOURCE, "states": STATES, "directions": DIRECTIONS}, indent=2))


if __name__ == "__main__":
    main()
