#!/usr/bin/env python3
"""Rebuild the HMH animated roster ledger/manifest from disk-truth PNG frames.

Use after PixelLab harvest/relabel passes. The runtime manifest must reflect the
actual `<actor>/<animation>/<direction>/*.png` directories, not stale queue-time
ledger coverage. Positional `animN` fragments are ignored.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ROSTER = ROOT / "apps/portal/assets/generated/hmh-animated-roster"
LEDGER = ROSTER / "roster-ledger.json"
MANIFEST = ROSTER / "hmh-animated-roster.mjs"
DIRECTIONS = ["south", "south-east", "east", "north-east", "north", "north-west", "west", "south-west"]
CANONICAL_ANIMS = [
    "idle", "walk", "run",
    "shoot", "shoot-shotgun", "melee", "throw", "levelup",
    "attack-tell", "attack", "attack-ranged", "hit", "hurt", "death", "spawn", "special",
]


def frame_src(actor: str, anim: str, direction: str, file_name: str) -> str:
    return f"./assets/generated/hmh-animated-roster/{actor}/{anim}/{direction}/{file_name}"


def build_actor_animations(actor_dir: Path) -> dict[str, dict[str, list[str]]]:
    animations: dict[str, dict[str, list[str]]] = {}
    for anim_dir in sorted([p for p in actor_dir.iterdir() if p.is_dir()]):
        if re.fullmatch(r"anim\d+", anim_dir.name):
            continue
        if anim_dir.name not in CANONICAL_ANIMS:
            continue
        dirs: dict[str, list[str]] = {}
        for direction in DIRECTIONS:
            d = anim_dir / direction
            if not d.is_dir():
                continue
            frames = [frame_src(actor_dir.name, anim_dir.name, direction, p.name) for p in sorted(d.glob("*.png"))]
            if frames:
                dirs[direction] = frames
        if dirs:
            animations[anim_dir.name] = dirs
    return animations


def main() -> None:
    prior: dict[str, Any] = json.loads(LEDGER.read_text(encoding="utf-8")) if LEDGER.exists() else {}
    # Start from the existing ledger so zero-animation/deferred actors remain
    # explicit debt rows for art-census and coverage reports. Then replace only
    # actors with disk-backed PNG directories so runtime frame paths are truthful.
    rebuilt: dict[str, Any] = dict(prior)
    for actor_dir in sorted([p for p in ROSTER.iterdir() if p.is_dir()]):
        animations = build_actor_animations(actor_dir)
        previous = prior.get(actor_dir.name, {})
        rebuilt[actor_dir.name] = {
            "role": previous.get("role", "enemy"),
            "character_id": previous.get("character_id"),
            "animations": animations if animations else previous.get("animations", {}),
        }
    LEDGER.write_text(json.dumps(rebuilt, indent=2), encoding="utf-8")
    body = json.dumps(rebuilt, indent=2)
    MANIFEST.write_text(
        "// AUTO-GENERATED by rebuild-hmh-animated-roster-from-disk.py. Do not hand-edit.\n"
        "// Disk-truth 8-direction animated character roster.\n"
        "// Shape: { <key>: { role, character_id, animations: { <name>: { <direction>: [framePaths] } } } }\n"
        f"export const HMH_ANIMATED_ROSTER = Object.freeze({body});\n",
        encoding="utf-8",
    )
    summary = {}
    for actor, entry in rebuilt.items():
        summary[actor] = {anim: len(dirs) for anim, dirs in entry["animations"].items()}
    print(json.dumps({"actors": len(rebuilt), "summary": summary}, indent=2))


if __name__ == "__main__":
    main()
