import { Application, Container, Graphics, Text } from 'pixi.js';
import { PIECE_CELLS, cellsFor, collides } from '../../portal/src/stacked-sim.mjs';
import { createStackedBoardView, PIECE_COLORS } from './render/board-view.mjs';
import { createStackedLocalInput } from './local-input.mjs';
import { createLocalStackedMatch } from './local-match.mjs';
import { recommendedLocalControls, localDevices, localBoardLayout } from './local-setup.mjs';

export async function mountLocalStacked() {
  const $ = id => document.getElementById(id), stage=$('stage'), panel=$('panel');
  const app = new Application();
  const events=new AbortController(),listen=(target,type,handler)=>target.addEventListener(type,handler,{signal:events.signal});
  let abandoned=false;const abandon=()=>{abandoned=true;};window.addEventListener('pagehide',abandon,{once:true});
  try { await app.init({width:1,height:1,autoStart:false,sharedTicker:false,background:0x070e18,preference:'webgl',resolution:Math.min(devicePixelRatio,2)}); }
  catch(error) { try { app.destroy(true); } catch { /* The renderer may not have initialized. */ } throw error; }
  finally { window.removeEventListener('pagehide',abandon); }
  if(abandoned){app.destroy(true);return;}
  stage.append(app.canvas);app.canvas.tabIndex=0;app.canvas.setAttribute('aria-label','Player one and player two STACKED boards');
  const views=[0,1].map(index=>createStackedBoardView({index,frame:'wide',geometry:{PIECE_CELLS,cellsFor,collides},Container,Graphics,Text}));
  for(const view of views){app.stage.addChild(view.root);view.layers.hudLayer.visible=false;view.setTrails(false);view.setColorblindPieces(true);}
  const hud=views.map((_,i)=>{const el=document.createElement('div');el.className='player-hud';el.innerHTML='<aside class="hold"><h3>HOLD</h3><div class="held piece"></div><div class="hud-score"><strong class="score">0</strong>points<br><span class="lines">0</span> lines</div><div class="incoming"><strong class="rows">0</strong>incoming rows</div></aside><aside class="queue"><h3>NEXT</h3><div class="next"></div></aside>';$('hud').append(el);return el;});
  let run=null, input=null, disposed=false, raf=0, setupMode=true, layout={playable:false,slots:[]}, lastTick=-1, lastStatus='', deviceScanAt=0, lastDeviceText='';
  const pads=()=>{try{return navigator.getGamepads?.()??[];}catch{return [];}};
  $('deviceChoice').value=recommendedLocalControls(pads());
  const guide={
    'keyboard-pad':[['Player one · Keyboard','← → move · ↓ soft drop','Space drop · ↑ / X rotate','Z reverse · V 180° · C hold'],['Player two · Controller','D-pad / stick move · down soft drop','A drop · B rotate · X reverse','Y 180° · LB hold · Menu pause']],
    'two-pads':[['Player one · Controller 1','D-pad / stick move · down soft drop','A drop · B rotate · X reverse','Y 180° · LB hold · Menu pause'],['Player two · Controller 2','D-pad / stick move · down soft drop','A drop · B rotate · X reverse','Y 180° · LB hold · Menu pause']],
    'split-keyboard':[['Player one · Left keys','A / D move · S soft drop · W drop','G rotate · F reverse','H 180° · T hold'],['Player two · Arrows + numpad','← → move · ↓ soft drop · ↑ drop','Numpad 3 rotate · 1 reverse','Numpad 2 180° · 0 hold']],
  };
  function updateGuide(){const choice=$('deviceChoice').value;$('ghosting').hidden=choice!=='split-keyboard';$('controlGuide').replaceChildren(...guide[choice].map(([heading,...rows])=>{const section=document.createElement('section'),h=document.createElement('h2');h.textContent=heading;section.append(h);for(const row of rows){const p=document.createElement('p');p.textContent=row;section.append(p);}return section;}));$('setupError').textContent='';}
  function scanDevices(){const list=Array.from(pads()).filter(p=>p?.connected&&p.mapping==='standard');const text=list.length?`${list.length} controller${list.length===1?'':'s'} detected. Release all buttons before starting.`:'Connect a controller and press any button, or choose Share one keyboard.';if(text!==lastDeviceText){$('deviceStatus').textContent=text;lastDeviceText=text;}}
  function show(title,copy){if(disposed)return;$('panelTitle').textContent=title;$('panelCopy').textContent=copy;if(!panel.open)panel.showModal();document.body.dataset.localState=setupMode?'setup':run?.snapshot().phase??'paused';}
  function pause(message='Both boards are paused. Ready when you are.',controls=false) {if(disposed||setupMode||!run||run.snapshot().phase==='complete')return;run.pause();controls ||= document.activeElement===$('controls');$('roundControls').hidden=!controls;if(controls){const guide=$('controlGuide').cloneNode(true);guide.removeAttribute('id');$('roundControls').replaceChildren(guide);}$('resume').hidden=false;$('rematch').hidden=true;show('Take a breather.',message);}
  function fit(){if(disposed)return;const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;app.renderer.resize(w,h);layout=localBoardLayout(w,h);$('resume').disabled=!layout.playable;$('resume').textContent=layout.playable?'Resume match':'Rotate to resume';views.forEach((v,i)=>v.resize(layout.slots[i]??{x:0,y:0,scale:1,visible:false}));$('hud').hidden=!layout.playable;if(!layout.playable&&!setupMode)pause('Rotate to landscape or use a wider screen. Both boards will wait.');}
  function piece(kind){const el=document.createElement('div');el.className='piece';if(!kind){el.textContent='—';el.classList.add('piece-empty');return el;}const cells=cellsFor(kind,0,0,0),xs=cells.map(c=>c[0]),ys=cells.map(c=>c[1]),minX=Math.min(...xs),maxY=Math.max(...ys);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 64 40');for(const [x,y] of cells){const r=document.createElementNS(svg.namespaceURI,'rect');r.setAttribute('x',String((x-minX)*14+4));r.setAttribute('y',String((maxY-y)*14+4));r.setAttribute('width','12');r.setAttribute('height','12');r.setAttribute('rx','2');r.setAttribute('fill','#'+PIECE_COLORS[kind].toString(16).padStart(6,'0'));r.setAttribute('stroke','#e4faff');r.setAttribute('stroke-width','.6');svg.append(r);}el.append(svg);return el;}
  function present(state){if(disposed)return;if(state.match.tick===lastTick)return;lastTick=state.match.tick;state.match.boards.forEach((board,i)=>{views[i].present(board);const el=hud[i];el.querySelector('.score').textContent=board.score.toLocaleString();el.querySelector('.lines').textContent=String(board.lines);el.querySelector('.rows').textContent=String(state.match.pendingAttacks[i].reduce((n,r)=>n+r.rows,0));const key=`${board.hold}/${board.queue.slice(0,5).join('')}`;if(el.dataset.pieces!==key){el.dataset.pieces=key;el.querySelector('.held').replaceChildren(piece(board.hold));el.querySelector('.next').replaceChildren(...board.queue.slice(0,5).map(piece));}});const sec=Math.floor(state.match.tick/60);$('matchClock').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;app.render();}
  function results(state){if(lastStatus==='complete')return;lastStatus='complete';$('roundControls').hidden=true;$('resume').hidden=true;$('rematch').hidden=false;$('roundStats').replaceChildren(...state.match.boards.map((b,i)=>{const section=document.createElement('section');const h=document.createElement('h2');h.textContent=`Player ${i+1}`;section.append(h);for(const text of [`${b.score.toLocaleString()} points`,`${b.lines} lines cleared`,`${b.piecesLocked} piece${b.piecesLocked===1?'':'s'} placed`]){const p=document.createElement('p');p.textContent=text;section.append(p);}return section;}));show(state.outcome.winner===null?'A perfect tie.':`Player ${state.outcome.winner+1} wins!`,'One more round? Both players get a fresh board and the same new piece sequence.');$('rematch').focus();}
  function resume(){if(disposed)return;if(!run||!layout.playable||document.hidden){$('panelCopy').textContent='Rotate to landscape or use a wider screen, then resume.';return;}panel.close();app.canvas.focus();if(!run.resume()){show('Reconnect your controls.','Choose New match / controls to reclaim devices and start together.');return;}lastStatus='running';document.body.dataset.localState='running';}
  function start(event){event?.preventDefault();if(disposed)return;$('setupError').textContent='';try{const devices=localDevices($('deviceChoice').value,pads());$('arena').hidden=false;$('matchFooter').hidden=false;fit();if(!layout.playable)throw Error('Two boards need landscape and a wider screen (at least 768 pixels).');run?.destroy();input=createStackedLocalInput({target:window,devices,onPause:()=>pause(),onDeviceLost:()=>pause('A controller disconnected. Choose New match / controls to reconnect and start together.')});const seed=crypto.getRandomValues(new Uint32Array(1))[0]||1;run=createLocalStackedMatch({seed,mode:'free',input});setupMode=false;lastTick=-1;lastStatus='';$('setup').hidden=true;$('roundActions').hidden=false;$('roundStats').replaceChildren();$('pause').hidden=false;for(const v of views)v.setColorblindPieces($('patterns').checked);present(run.snapshot());resume();}catch(error){$('setupError').textContent=error.message;}}
  function setup(){if(disposed)return;run?.destroy();run=null;input=null;setupMode=true;lastTick=-1;lastStatus='';$('arena').hidden=true;$('matchFooter').hidden=true;$('pause').hidden=true;$('setup').hidden=false;$('roundActions').hidden=true;$('setupError').textContent='';updateGuide();scanDevices();show('Two players. One screen.','Same pieces. Separate boards. Clear lines to send rows across. Last player standing wins.');}
  function frame(now){if(disposed)return;if(now-deviceScanAt>500&&setupMode){scanDevices();deviceScanAt=now;}if(run){const state=run.advance(now);present(state);if(state.phase==='complete')results(state);else if(state.phase==='paused'&&!panel.open)pause();}raf=requestAnimationFrame(frame);}
  const visibility=()=>{if(document.hidden)pause('The tab was hidden. Both boards are paused.');};
  const resize=()=>{fit();if(run){lastTick=-1;present(run.snapshot());}};
  const dispose=()=>{if(disposed)return;disposed=true;events.abort();cancelAnimationFrame(raf);run?.destroy();window.removeEventListener('resize',resize);document.removeEventListener('visibilitychange',visibility);views.forEach(v=>v.destroy());app.destroy(true);document.body.dataset.localDisposed='true';};
  listen($('setup'),'submit',start);listen($('deviceChoice'),'change',updateGuide);listen($('pause'),'click',()=>pause());listen($('resume'),'click',resume);listen($('rematch'),'click',start);listen($('changeControls'),'click',setup);
  listen($('controls'),'click',()=>pause('Both boards are paused. Here are your controls.',true));
  listen(panel,'cancel',event=>event.preventDefault());listen(window,'resize',resize);listen(document,'visibilitychange',visibility);listen(window,'pagehide',dispose);
  $('notice').hidden=true;setup();raf=requestAnimationFrame(frame);
  // A read-only view for the existing browser smoke; no setters, evidence or secrets.
  return Object.freeze({snapshot:()=>({disposed,state:run?.snapshot()??null,playable:layout.playable}),destroy:dispose});
}
